name: Train Model

on:
  pull_request:
    branches:
      - '*'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

# TODO: seed?
    - name: Train model
      run: |
        HYDRA_FULL_ERROR=1 python src/train.py \
          model=mistral \
          trainer=cpu \
          trainer.max_epochs=2 \
          data=example_data \
          data.data_dir=data \
          data.batch_size=2 \
          data.num_workers=0 \
          data.max_tokens=5000 \
          data.gym_data_dir="tiny_data/ProteinGym" \
          logger=null_logger \
          +trainer.num_sanity_val_steps=0 \
          trainer.val_check_interval=1.0 \
          trainer.target_tokens_per_batch=null \
          'model.config.hidden_size=4' \
          'model.config.intermediate_size=4' \
          'model.config.num_attention_heads=1' \
          'model.config.num_hidden_layers=1' \
          'model.config.num_key_value_heads=1' \
          'data.dataset_cfgs.interpro.data_path_pattern="tiny_data/interpro/protein-matching-*.fasta"' \
          'data.dataset_cfgs.openfold_aligned.data_path_pattern="tiny_data/openfold/uniclust30_filtered/*/a3m/*.a3m"' \
          'data.dataset_cfgs.openfold_raw.data_path_pattern="tiny_data/openfold/uniclust30_filtered/*/a3m/*.a3m"' \
          'data.dataset_cfgs.ec.data_path_pattern="tiny_data/expasy_ec/*.fasta"'
