name: Train Model

on: [push]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        python src/train.py \
          model=mistral \
          trainer=cpu \
          trainer.max_epochs=2 \
          data=example_data \
          data.batch_size=2 \
          data.num_workers=1 \
          data.max_tokens=300 \
          logger=null_logger \
          'model.config.hidden_size=4' \
          'model.config.intermediate_size=4' \
          'model.config.num_attention_heads=1' \
          'model.config.num_hidden_layers=1' \
          'model.config.num_key_value_heads=1' \
          'data.dataset_cfgs.interpro.data_path_pattern="data/example_data/interpro/protein-matching-*.fasta"' \
          'data.dataset_cfgs.openfold_aligned.data_path_pattern="data/example_data/openfold/uniclust30_filtered/*/a3m/NO_PATH"' \
          'data.dataset_cfgs.openfold_raw.data_path_pattern="data/example_data/openfold/uniclust30_filtered/*/a3m/NO_PATH"' \
          'data.dataset_cfgs.ec.data_path_pattern="data/example_data/expasy_ec/1_1_1_4.fasta"'
