name: Train Model

on:
  workflow_dispatch:
  pull_request:
    branches: [master, main]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt --system

# TODO: seed?
    - name: Test
      run: |
        pytest -k "not example"
    - name: Train model
      run: |
        HYDRA_FULL_ERROR=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 \
          python src/train.py \
            data=train_example \
            model=llama_test \
            trainer=cpu \
            trainer.max_steps=2 \
            +trainer.num_sanity_val_steps=0 \
            +trainer.limit_val_batches=1 \
            +trainer.enable_checkpointing=false \
            logger=stdout \
            callbacks=none \
            data.num_workers=0 \
            data.prefetch_factor=null
